name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Git Install
      run: 
        echo Installing Git...
        apt install git
    - name: Install of Pi/Python Component packages
      run: 
        echo Installing Python packages...
        pip install keyboard
        apt-get install python-picamera python3-picamera
    - name: Build image
      run: 
        echo building image...
        docker build github.com/ethanwllms/QC-Project/QC-Pi
        docker push ethanwllms/qc_project-latest
